### ISSUE TITLE
Memory leak in ViewRootImpl$4 while executing :recordPaparazzi

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#305] opened 2021-11-06 22:51 UTC
I was running a test class that has about 130 tests. I'm using the default setup of Gradle test execution, which gives -Xmx512m.
After about 6 minutes of running `gradlew :component:widget:recordPaparazzi` the tests start OOM-ing.
![image](https://user-images.githubusercontent.com/2906988/140626034-ea619566-5818-427b-b327-f4e78c4a35f5.png)
I took a heap dump and it shows that ViewRootImpl$4 is dominating.
![image](https://user-images.githubusercontent.com/2906988/140625969-4a0db04a-6af9-4f30-8d5e-246fc667a19e.png)
Path to GC root
![image](https://user-images.githubusercontent.com/2906988/140625972-702eaa38-e0fa-4c56-be56-dd90a8bf5d83.png)
From these it looks like `ViewRootImpl.loadSystemProperties` posts a Runnable that has a `this$0` reference to the outer class, but this is never removed from the handler (never executed?).

Code: https://github.com/TWiStErRob/net.twisterrob.sun/tree/paparazzi_leak

**Comment by TWiStErRob** [comment] 2021-11-07 09:16
Confirmed with:
```
tasks.withType<Test>().configureEach {
	maxHeapSize = "1G"
}
```
it runs to completion, but heap keeps climbing till the end.

**Comment by jrodbx** [comment] 2021-11-20 05:32
Thanks for the analysis!

Looks like 0.8.0 indeed leaks HandlerMessageQueue callbacks per the Path to GC root analysis you showed.

Fortunately, this appears fixed as of https://github.com/cashapp/paparazzi/pull/286.

As a result of this line: https://github.com/cashapp/paparazzi/blob/dd89a76a480703d25af668444c8723a48b70ac59/paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt#L275

I repro'd and confirmed the fix with your helpful tips (pointing to mavenLocally-deployed temp builds):
```
$ git clone git@github.com:TWiStErRob/net.twisterrob.sun.git
$ cd net.twisterrob.sun
$ git checkout paparazzi_leak
$ ./gradlew :component:widget:recordPaparazzi
```

Heap analysis before the commit (fb34352bad35360ea23603f4fea4b798afec8d7a):
<img width="1174" alt="Screen Shot 2021-11-20 at 12 28 17 AM" src="https://user-images.githubusercontent.com/1868149/142715645-b2928ed8-71ac-4fb4-bdc7-a38ee3d4c094.png">


Heap analysis after the commit (dd89a76a480703d25af668444c8723a48b70ac59):
<img width="1176" alt="Screen Shot 2021-11-20 at 12 19 01 AM" src="https://user-images.githubusercontent.com/1868149/142715646-a8fa3c45-4b95-4641-9c0c-f3c4329fae92.png">

**Closed by jrodbx** 2021-11-20 05:32 UTC
