### ISSUE TITLE
Unable to capture snapshot using coroutine flow

### ISSUE THREAD

**Issue by hrcronin** [cashapp/paparazzi#1236] opened 2024-01-17 16:54 UTC
**Description**
I have a custom composable component that allows for a parameter with type Flow<Boolean>. Using this syntax I am unable to capture a snapshot of it.

**Steps to Reproduce**
Custom Composable Component
```
@Composable 
fun CustomComponent(
  state: Flow<Boolean>
  modifier: Modifier = Modifier
) {
   val isEnabled by viewModel.value.collectAsState(initial = false)
   Text(text = "is enabled = $isEnabled")
}
```
This test always captures: "is enabled = false"
```
class MyTest {
   @get:Rule
    var paparazzi = Paparazzi(
        deviceConfig = PIXEL_5,
        theme = "android:Theme.Material.Light.NoActionBar"
    )

    @Test
    fun testWithFlow() {
       paparazzi.snapshot {
             val dataFlow = MutableStateFlow(true)
             CustomComponent(dataFlow)
       }
    }
}
```

**Expected behavior**
I would expect this to still capture the state of the composable in the true state. I looked through all the samples and documentation, but couldn't find anything helpful for this situation. How can I capture the state of the composable in this scenario when true is emitted on the composable?

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: mac OS ventura 
- Compile SDK: 34
- Gradle Version: 8.1
- Android Gradle Plugin Version: 8.1.4

**Screenshots**

**Comment by kozaxinan** [comment] 2024-01-17 17:17
Where does viewModel field comes? 
Sample doesnt look like it is complete example.
What is the output you get from the test?

**Comment by jrodbx** [comment] 2024-01-17 18:29
@hrcronin mind providing a small sample project?  to @kozaxinan's point, I don't know where viewmodel comes from.

**Comment by hrcronin** [comment] 2024-01-17 21:00
Apologies the code snippets were incomplete. Here is the full implementation of the compose view component:
```
@Composable
fun CustomComponent(
    state: Flow<Boolean>,
    modifier: Modifier = Modifier
) {
    val isEnabled by state.collectAsState(initial = false)
    Text(text = "is enabled = $isEnabled", modifier = modifier)
}

@Preview(
    showBackground = true,
    backgroundColor = 0xFFFFFFFF
)
@Composable
fun PreviewWithEnabled() {
    CustomComponent(state = flowOf(true))
}

@Preview(
    showBackground = true,
    backgroundColor = 0xFFFFFFFF
)
@Composable
fun PreviewWithDisabled() {
    CustomComponent(state = flowOf(false))
}
```

Here is a screenshot of each preview.
<img width="163" alt="image" src="https://github.com/cashapp/paparazzi/assets/12897010/6cbac121-472d-4a23-876b-3b30fc2fc71c">

However, if I run `PreviewWithEnabled` in Interactive Mode, it automatically changes to the following screenshot.
<img width="134" alt="image" src="https://github.com/cashapp/paparazzi/assets/12897010/442726e5-200a-4377-b1ba-a04979d99f0e">

When I capture this using a PaparazziTest:
Note: I expect this to be "true"
<img width="314" alt="image" src="https://github.com/cashapp/paparazzi/assets/12897010/170165b5-9bd9-4ec0-8adc-a23b2436029b">

**Comment by jrodbx** [comment] 2024-01-17 22:07
This is correct behavior.  Paparazzi is acting like the Previews do, in non-interactive mode, i.e., capturing the 1st frame only.

Interactive mode allows for animations, so in a subsequent (second?) frame, the initial state emitted as "false" is followed by an emission of "true".

Stay tuned for a release where Paparazzi will support animations through gif support for this type of functionality.

Closing as duplicate of https://github.com/cashapp/paparazzi/issues/496

**Closed by jrodbx** 2024-01-17 22:07 UTC
Labels: waiting on user

**Comment by hrcronin** [comment] 2024-01-18 02:05
Thank you for the quick response with the additional information. I'll keep an eye on the releases for future updates here.
