### ISSUE TITLE
ConstraintLayout 1.1.0-alpha12 "Width (0) and height (0) cannot be <= 0" error or font resource loading error or  empty screenshot issue 

### ISSUE THREAD

**Issue by alashow** [cashapp/paparazzi#1054] opened 2023-08-22 01:59 UTC
**Description**
When upgrading from `androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha05` to `1.1.0-alpha-12` (or any versions in between), screenshot tests start failing (even the tests that don't use constraintlayout)

**Steps to Reproduce**
Apply `androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha12` dependency

Screenshot tests fail with different reasons:
```kotlin
Variant 1:
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
        at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
        at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:519)
        at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:451)
        at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:314)
        at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:313)
        at app.cash.paparazzi.Paparazzi.withTime(Paparazzi.kt:361)
        at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:313)
        at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:207)
        at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:206)
        at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:202)

Variant 2
java.lang.IllegalStateException: Could not load font
	at androidx.compose.ui.text.font.TypefaceRequestCache.runCached(FontFamilyResolver.kt:200)
	at androidx.compose.ui.text.font.FontFamilyResolverImpl.resolve(FontFamilyResolver.kt:92)
	at androidx.compose.ui.text.font.FontFamilyResolverImpl.resolve-DPcqOEQ(FontFamilyResolver.kt:79)
	at androidx.compose.foundation.text.HeightInLinesModifierKt$heightInLines$2.invoke(HeightInLinesModifi
...
android.content.res.Resources$NotFoundException: Font resource ID #0x7f09000f could not be retrieved.
```

or Variant 3, empty rendering:
<img src="https://github.com/cashapp/paparazzi/assets/5840013/1bfd39ab-53a1-447b-9052-dc13a0f48afa" width="45%"></img> <img src="https://github.com/cashapp/paparazzi/assets/5840013/8a9f9245-1166-4cc5-bc98-0f24c515bf6a" width="45%"></img> 

(Interestingly enough, for empty ones it keeps/renders background color from theme)

**Expected behavior**
Screenshot tests to not break

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: osx, 13.4.1 
- Compile SDK: 33 or 34
- Gradle Version: 8.1.0 or 8.2.1-alpha16
- Android Gradle Plugin Version: 8.1.0 or 8.2.0-alpha16

**Screenshots**

**Comment by jrodbx** [comment] 2023-08-31 00:09
Seen also on CashApp, investigating

**Comment by ivannarino** [comment] 2023-09-12 08:48
I had this issue a bit randomly on my CI, I didn't commit some flaky screenshots that didn't fail the build locally. After generating all the snapshots and pushing them to remote, the errors went away.

It may not resolve your issue, but thought it would be nice add my feedback.

**Comment by ivannarino** [comment] 2023-09-15 13:13
Managed to make it work only rebuilding the PR from the same commit. So it's flaky

**Comment by jrodbx** [comment] 2023-09-15 20:52
Having some trouble repro'ing this issue, has anyone found a recipe?

**Comment by mrmike** [comment] 2023-09-18 10:44
I didn't find what exactly is causing the issue but disabling cache with `--no-build-cache` while running verify task fixed the issue in my case.

**Comment by mrmike** [comment] 2023-09-18 13:36
Together with @ivannarino, we've dug more into the issue and found out that there's some caching issue when using the new resource loading mechanism.

We've noticed that snapshot verification only fails when output for the task `preparePaparazziDebugResources` comes from the cache. When a task was executed, snapshot verification worked as expected (this explains why adding `--no-build-cache` fixes the issue).

After checking that Paparazzi `1.3.1` introduced a new resource/asset loading mechanism I've switched to the legacy one using
```
app.cash.paparazzi.legacy.resource.loading=true
app.cash.paparazzi.legacy.asset.loading=true
```
and with the legacy mechanism, everything is working ok. 

Hopefully, this will help find the root cause of this issue. Also, let me know If I can provide any more details.

**Comment by mrmike** [comment] 2023-09-19 13:26
I'm adding a couple more findings that helped me reproduce the issue on my local machine (with some manual modifications)

1. In my project I use fonts provided in the resources of the external AAR library
2. Enable the new resource loading mechanism to make sure Paparazzi is not using `merged_res` directories
3. In the Gradle cache (`.gradle/caches`) find the corresponding entry for the library that provides fonts (make sure cache is populated)
4. Manually remove fonts (sample path `.gradle/cache/transforms-3/a8b69e7d0b4f9fbed8763a56c9bccf70/transformed/{libraryName-version}/res/font/`)
5. Run `verifyPaparazziDebug` task to get 
    ```
    java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
    ```
    and 
    ```
    java.lang.IllegalStateException: Could not load font
    ```
    exceptions. 

Originally I was getting those exceptions only on CI, never on my local machine so I assume this could be somehow related to the Gradle cache state on the CI.

**Comment by jrodbx** [comment] 2024-01-13 18:33
Update:

I've spent considerable time investigating this and I _think_ this was ultimately a Gradle caching bug, addressed here: https://github.com/cashapp/paparazzi/pull/1226

Can someone try the latest snapshot and confirm that this is now solved?

In the meantime, I'll move this into the next milestone as I'd like to move forward with a release.

**Comment by mrmike** [comment] 2024-01-15 08:17
Hi @jrodbx 

I was trying to reproduce the issue using the latest version of Paparazzi but I've encountered different exception
```
java.lang.IllegalAccessError: class com.android.resources.ResourceType tried to access method 'java.util.stream.Collector com.google.common.collect.Sets.toImmutableEnumSet()' (com.android.resources.ResourceType and com.google.common.collect.Sets are in unnamed module of loader 'app')
	at com.android.resources.ResourceType.<clinit>(ResourceType.java:175)
	at app.cash.paparazzi.internal.DynamicResourceIdManager$IdProvider.<init>(DynamicResourceIdManager.kt:14)
	at app.cash.paparazzi.internal.DynamicResourceIdManager.<init>(DynamicResourceIdManager.kt:28)
	at app.cash.paparazzi.internal.PaparazziCallback.<init>(PaparazziCallback.kt:52)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:155)
	at app.cash.paparazzi.Paparazzi$apply$1.evaluate(Paparazzi.kt:142)
```

I think this might be somehow related to the Guava version bump but I'll need to spend more time to investigate this exception.

**Comment by TWiStErRob** [comment] 2024-01-15 08:27
@mrmike Start by searching this repo's issues, you'll be surprised ;)

**Comment by TWiStErRob** [comment] 2024-01-15 19:04
@mrmike see full report and workaround for that issue: https://github.com/cashapp/paparazzi/issues/1231

**Comment by mrmike** [comment] 2024-01-15 20:57
With the workaround applied I was not able to reproduce the issue. Thanks @TWiStErRob for providing the link :)

**Comment by jrodbx** [comment] 2024-01-16 05:16
Closing as fixed!

**Closed by jrodbx** 2024-01-16 05:16 UTC
Labels: bug, waiting on user

**Comment by alashow** [comment] 2024-02-07 00:08
Sorry for coming to this late, but I'm still seeing this issue with 1.3.2.

@mrmike Were you still seeing width/height issues before upgrading to 1.3.2? Because for me 1.3.2 only introduced https://github.com/cashapp/paparazzi/issues/1054#issuecomment-1891537714 issue, and the workaround was only for guava.

**Comment by alashow** [comment] 2024-02-07 01:29
Apparently now this problem shows up even with composeBom version `2024.01.00`
