### ISSUE TITLE
Snapshot without a device frame

### ISSUE THREAD

**Issue by swankjesse** [cashapp/paparazzi#37] opened 2019-04-05 15:56 UTC
Perhaps something like this:

```
    paparazzi.snapshot(avatar, "avatar", deviceFrame = DeviceFrame.NONE)
```

**Comment by nikwotton** [comment] 2019-12-19 01:42
+1

**Comment by TWiStErRob** [comment] 2022-12-14 10:09
Is this a duplicate of https://github.com/cashapp/paparazzi/issues/313?

**Comment by TWiStErRob** [comment] 2022-12-14 10:52
Isn't testing a widget (`View` with specific w/h) the same as testing a composable `Button`?

**Closed** 2022-12-14 16:24 UTC
