### ISSUE TITLE
Paparazzi 1.1.0 does not work with compose 1.3.0

### ISSUE THREAD

**Issue by marektrzesniewski** [cashapp/paparazzi#649] opened 2022-12-09 15:48 UTC
**Description**
I can't run paparazzi tests when using compose 1.3.0. After downgrading the compose library to version 1.2.0 everything works correctly.

This is my repository: https://github.com/marektrzesniewski/PaparazziHelloTests

You can reproduce this behavior on branch: paparazzi_fail_with_compose_1_3_0 https://github.com/marektrzesniewski/PaparazziHelloTests/tree/paparazzi_fail_with_compose_1_3_0 

**Steps to Reproduce**
1. Clone my repo on branch paparazzi_fail_with_compose_1_3_0 and run in console: ./gradlew feature-module:testDebug --info.

I had these problems in the console:

-  PM app.cash.paparazzi.internal.PaparazziLogger error SEVERE: broken: View measure failed
    java.lang.IllegalStateException: layout state is not idle before measure starts
-  PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: broken: View measure failed
    java.lang.NullPointerException
    at androidx.core.os.BuildCompat.isAtLeastPreReleaseCodename(BuildCompat.java:60)

**Expected behavior**
Test should pass

**Additional information:**
- Paparazzi Version: 1.1.0
- OS: tested on macOS Ventura 13.0 and on Windows 10
- Compile SDK: 32 and 33
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.3.1

**Screenshots**
![image](https://user-images.githubusercontent.com/106925755/206739471-f75fd34c-cd0f-4d5f-b5c5-e1d2efb11c12.png)
![image](https://user-images.githubusercontent.com/106925755/206739538-abed67a7-4c42-4415-a3eb-97b7b0c8f98e.png)

I have also tried upgrading compose to 1.3.2 but there is the same effect as with version 1.3.0

**Comment by JakeWharton** [comment] 2022-12-09 15:55
Duplicate of #604. The fix is already merged. Please try the latest snapshot and confirm that it's working for you.

**Closed by JakeWharton** 2022-12-09 15:55 UTC
Labels: bug
