### ISSUE TITLE
Allow customization for video/image file names

### ISSUE THREAD

**Issue by eboudrant** [cashapp/paparazzi#1243] opened 2024-01-19 19:22 UTC
Currently the filename is computed from:
```
"${testName.packageName}${delimiter}${testName.className}${delimiter}${testName.methodName}$formattedLabel.$extension"
```
This can generate, in your module, a very large flat directory structure, making it hard to navigate and to read in lot of UI tools since the most interesting part of the filename is at the end (class name, test name and parameters). If I take a git tool like SourceTree, the only think you might see in their UI is the file package name, rest is truncated require horizontal scrolling. Same when you browse snapshot in Android Studio.

Would be nice to allow configuration for the filename. In my case I would probably "minify" package names and create directory structure for class names.

**Comment by jrodbx** [comment] 2024-01-19 21:18
Duplicate of #549

**Closed by jrodbx** 2024-01-19 21:18 UTC
Labels: enhancement
