### ISSUE TITLE
[FEATURE] Publish layoutlib source code

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#448] opened 2022-06-05 11:27 UTC
**Description**
Whenever there's an exception the stacktrace shows line numbers, but when I click on them they never show the actual line, because IDEA decompiles .class files, so it gets misaligned.

**Steps to Reproduce**
Do something that breaks the internals, e.g. getSystemService() for an unsupported service by `BridgeContext`. But have faces this problem in many other scenarios.

**Actual behavior**
layoutlib-native-jdk11-2021.1.1-573f070-sources.jar contains 1 file: `META-INF/MANIFEST.MF` with contents `Manifest-Version: 1.0`.

**Expected behavior**
Navigable source code.

**Additional information:**
- Paparazzi Version: 1.0
- OS: Windows
- Compile SDK: 31
- Gradle Version: 7.4.2
- Android Gradle Plugin Version: 7.2.1

**Comment by jrodbx** [comment] 2022-06-05 12:17
Duplicate of #214

**Closed** 2022-06-05 12:17 UTC
