### ISSUE TITLE
The name of the screenshot file

### ISSUE THREAD

**Issue by michwar** [cashapp/paparazzi#1033] opened 2023-08-02 06:43 UTC
**Description**
I found a problem with file names when we have already added some golden screen values to our repo but then we want to add another one, the previous one may change its name which causes a lot of changes in git history. 
The problem causes an integer number placed before a group name.
e.g. {path}[**1**.{groupName}:{name},1.1,1.light]
The integer number should not be associated with the <name> to not affect other previews?

Is there any way to define screen name by myself? Or add any regex or change the current pattern?
Or other way that will not change the old value when we add now one.

**Steps to Reproduce**
Add some golden values. Push them to the repo. Add another preview, generate golden values for them.

**Expected behavior**
The new files should not affect on the old ones.

**Additional information:**
- Paparazzi Version: 1.3.1
- Compile SDK: 33
- Android Gradle Plugin Version: 8.1.0

**@edit**
I found that the problem is caused by @PreviewParameter. When composable preview has a @PreviewParameter argument, the method name contains an integer but in non-deterministic way. Thats why after any change in previews many of screenshot files change their names

**Comment by SumeraMartin** [comment] 2023-08-11 10:03
I just found out that I have the same problem. It seems like that all of my previews has this index in the name even when only few of them are using preview parameter so not sure if it is related. But I'm using MultiPreview so that could be the issues.

I did some small change which moved all the indexes and suddenly almost all of my previews are marked as changed due filename change. I wonder if this is related to Paparazzi or Showkase 🤔

**Comment by SumeraMartin** [comment] 2023-08-11 10:53
Also, as I feel that it is related to this, it would be nice to be able to customize the name of the snapshot. My app has a long a package name which causes that name is too long without any additional value.

**Comment by michwar** [comment] 2023-08-11 12:04
As I found in the code the part {test_name}[{index}{showkase_name}] is the method name because the delimiter is `delimiter: String = "_"`
Try to override `ComponentPreview.toString()` and return `ShowkaseBrowserComponent.componentKey`

**Comment by SumeraMartin** [comment] 2023-08-11 12:56
I'm already doing this:

```
data class ScreenshotTestData(
    val component: ShowkaseBrowserComponent,
    val isDarkMode: Boolean,
    val fontSize: Float,
) {
    override fun toString(): String {
        val key = component.componentName
        val darkMode = if (isDarkMode) "1" else "0"
        return "${key}_d=${darkMode}_fs=$fontSize"
    }
}
```

This generates a string like `MainButtonPreview1 - 0_d=0_fs=1.0`. The `[1.{}]` and other parts are generated by Paparazzi.

However, I've just realized that in my case, the reason this index is present isn't due to `PreviewParameter`, but rather `TestParameter` from the `TestParameterInjector` library. I've drawn inspiration from this combination of tools: https://proandroiddev.com/automatic-screenshot-testing-for-all-your-compose-previews-6add202fecc7, which includes Paparazzi, Showkase, and TestParameterInjector.

**Comment by SumeraMartin** [comment] 2023-09-06 09:01
I was able to solve my issue by realising that some of my previews had the same name so TestParameterInjection automatically added indexing. When I get rid of these then it started to work fine.

**Comment by jrodbx** [comment] 2024-01-19 21:18
Duplicate of #549

**Closed by jrodbx** 2024-01-19 21:18 UTC
Labels: bug
