### ISSUE TITLE
Support custom fonts when constructing views in code

### ISSUE THREAD

**Issue by jrodbx** [cashapp/paparazzi#119] opened 2020-01-14 16:08 UTC
```
  // fails
  @Test
  fun textViewInCode() {
    val textView = AppCompatTextView(paparazzi.context).apply {
      typeface = ResourcesCompat.getFont(context, R.font.cashmarket_medium)
      text = "Hello, world!"
    }

    paparazzi.snapshot(textView, "text in code")
  }

  // passes
  @Test
  fun textViewInXml() {
    val textView = paparazzi.inflate<TextView>(R.layout.textview)
    paparazzi.snapshot(textView, "text in xml")
  }
```

related xml for the latter:
```
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:fontFamily="@font/cashmarket_medium"
    android:text="Hello, world!"
    tools:ignore="HardcodedText"
    />
```

**Comment by saket** [comment] 2020-05-08 17:34
Did some investigation today. The root of the problem seems to be that `ResourcesCompat` expects font resource paths to always start with `res/`:

```kotlin
final String file = value.string.toString();
if (!file.startsWith("res/")) {
    // Early exit if the specified string is unlikely to be a resource path.
    if (fontCallback != null) {
        fontCallback.callbackFailAsync(
                FontRequestCallback.FAIL_REASON_FONT_LOAD_ERROR, handler);
    }
    return null;
}
Typeface typeface = TypefaceCompat.findFromCache(wrapper, id, style);
```

With LayoutLib, resources always use an absolute path on the file system. E.g.: `~/<project path>/build/intermediates/merged/debug/font/custom_font.ttf`

The problem can be reproduced on Android Studio's layout preview as well if a custom view is used in xml that loads font using `ResourcesCompat`:

```kotlin
class FontTextView(context: Context, attrs: AttributeSet) : AppCompatTextView(context, attrs) {
  init {
    typeface = ResourcesCompat.getFont(context, R.font.custom_font)
  }
}
```

Setting `android:fontFamily` in xml on `AppCompatTextView` does not run into this issue because the attribute is read by `TextView` that uses framework APIs to load fonts. The framework APIs work nicely with layoutlib.

**Comment by saket** [comment] 2020-05-08 18:41
Filed an issue for this: https://issuetracker.google.com/issues/156065472

**Closed** 2020-06-05 06:59 UTC
