### ISSUE TITLE
AndroidX Core v1.10.1 breaks Paparazzi

### ISSUE THREAD

**Issue by juan-wesper** [cashapp/paparazzi#904] opened 2023-05-30 16:48 UTC
Using Paparazzi v1.2.0

Upgrading AndroidX Core to v1.10.1 (latest stable release) breaks all our Paparazzi unit tests.

Tests crash with the following stacktrace:
```

java.lang.NoClassDefFoundError: Could not initialize class androidx.core.os.BuildCompat
	at androidx.compose.ui.text.android.BoringLayoutFactory.measure(BoringLayoutFactory.kt:49)
	at androidx.compose.ui.text.android.LayoutIntrinsics.getBoringMetrics(LayoutIntrinsics.kt:55)
	at androidx.compose.ui.text.android.LayoutIntrinsics.getMaxIntrinsicWidth(LayoutIntrinsics.kt:82)
	at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics.getMaxIntrinsicWidth(AndroidParagraphIntrinsics.android.kt:64)
	at androidx.compose.ui.text.MultiParagraphIntrinsics$maxIntrinsicWidth$2.invoke(MultiParagraphIntrinsics.kt:82)
	at androidx.compose.ui.text.MultiParagraphIntrinsics$maxIntrinsicWidth$2.invoke(MultiParagraphIntrinsics.kt:80)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
<redacted - too long>
```

**Comment by TWiStErRob** [comment] 2023-05-30 16:59
Looking at https://github.com/androidx/androidx/commit/fec34088d1b323b19e1c2aef91a353eeab3ac394 which was merged for https://issuetracker.google.com/issues/276491001, it looks like the code was recently changed, after the 1.10.1 release. So upgrading to `1.11.0-alpha03` might fix your problem.

```
java.lang.NoClassDefFoundError: Could not initialize class androidx.core.os.BuildCompat
```
type exceptions are usually followed by the reason why the class is not found, from memory it would look something like this
```
Caused by: java.lang.ExceptionInInitializerError: ...
...
Caused by: <real cause>
```

Because we're talking about BuildCompat here, I think your issue might be a duplicate of https://github.com/cashapp/paparazzi/issues/758 which would show up as the `<real cause>`.

This was fixed recently. Can you please try the latest snapshot to see if it fixes the crash? https://github.com/cashapp/paparazzi#releases

**Comment by TWiStErRob** [comment] 2023-05-30 21:25
@geoff-powell do you think https://github.com/cashapp/paparazzi/pull/765 solved this, or was it something else?

**Comment by geoff-powell** [comment] 2023-05-31 00:22
@TWiStErRob yep that method should be available now with the PR you mentioned .

**Closed** 2023-05-31 00:24 UTC
Labels: bug
