### ISSUE TITLE
Vertically scrollable component was measured with an infinity maximum height constraints

### ISSUE THREAD

**Issue by rafsanjani** [cashapp/paparazzi#1364] opened 2024-03-29 21:00 UTC
**Description**
I have a basic setup in Jetpack Compose: a Column containing 100 items. I want to capture a vertically scrolling snapshot using Paparazzi, ensuring all items are visible. However, I encounter an `IllegalStateException`. 

This exception typically occurs in Compose when nesting a LazyColumn within another LazyColumn without specifying a height for the child LazyColumn. Hence, I suspect Paparazzi is embedding my content within either a Column (with verticalScroll modifier) or a LazyColumn.

**Steps to Reproduce**
I have a very simple Paparazzi setup.  Changing the `renderingMode` to `NORMAL` or `SHRINK`  will take the screenshot but only the visible portions of the screen are rendered. I want to render the whole `Column` and it's children. Replacing the `Column` with a `LazyColumn` produces the same outcome.

```
class LaunchViewTest {
    @get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = PIXEL_5,
        renderingMode = SessionParams.RenderingMode.V_SCROLL,
    )

    @Test
    fun launchComposable() {
        paparazzi.snapshot {
            MaterialTheme {
                Surface {
                    Column(
                        modifier = Modifier
                            .fillMaxSize()
                            .verticalScroll(rememberScrollState())
                    ) {
                        repeat(100) {
                            Text(text = "Hello $it")
                        }
                    }
                }
            }
        }
    }
}
```

**Expected behavior**
Take a long snapshot showing a list of 100 items.

**Additional information:**
- Paparazzi Version: 1.3.3
- OS: MacOs Sonoma
- Compile SDK: 34
- Gradle Version: 8.6
- Android Gradle Plugin Version: 8.2.2

**Screenshots**
RenderingMode.NORMAL
<img width="309" alt="image" src="https://github.com/cashapp/paparazzi/assets/9197459/7c6feec2-e577-44c0-a6ad-86c42a8e185b">

RenderingMode.SHRINK
<img width="303" alt="image" src="https://github.com/cashapp/paparazzi/assets/9197459/a0e2e262-d3e4-43ae-8f07-acd6c1eb9366">

**Comment by gamepro65** [comment] 2024-04-18 15:10
This is expected behavior.

When you use Modifier.fillMaxSize() in conjunction with V_SCROLL you are telling compose to take up all available space given which is going to be larger than Compose allows. Compose packs their Size's width and height into a single Long so they impose strict limits. If you drop fillMaxSize() everything should work out as you'd expect. 

While we could limit the max size we allow we allow to play nice with Compose you still wouldn't end up with the expected snapshot (ie wrapping your content) because fillMaxSize() will go beyond your Column's content resulting in a bunch of empty space.

**Comment by jrodbx** [comment] 2024-05-24 14:00
Closing as resolved

**Closed by jrodbx** 2024-05-24 14:00 UTC
Labels: bug

**Comment by nhaarman** [comment] 2024-06-28 08:56
Then why does this test result in the same exception? 🤔 

```
 paparazzi.snapshot {
            Box {
                LazyColumn {
                    items(1000) {
                        Text("Foo")
                    }
                }
            }
        }
```

**Comment by mxalbert1996** [comment] 2024-10-01 07:05
Compose UI checks infinite max constraint for all scrollable components (`Modifier.verticalScroll`, `LazyColumn`, etc.).
What we did to work around this is to use MockK to disable the check in snapshot tests:
```Kotlin
mockkStatic(::checkScrollableContainerConstraints)
every { checkScrollableContainerConstraints(any(), any()) } just Runs
```

**Comment by emartynov** [comment] 2024-10-02 06:58
> Compose UI checks infinite max constraint for all scrollable components (`Modifier.verticalScroll`, `LazyColumn`, etc.). What we did to work around this is to use MockK to disable the check in snapshot tests:
> 
> ```kotlin
> mockkStatic(::checkScrollableContainerConstraints)
> every { checkScrollableContainerConstraints(any(), any()) } just Runs
> ```

Interesting - let me try something similar. Thanks for the suggestion!
