### ISSUE TITLE
Don’t resize snapshots to 1000px

### ISSUE THREAD

**Issue by sdoward** [cashapp/paparazzi#482] opened 2022-07-02 16:40 UTC
**Description**
When recording content that is takes up a lot of height. The images that are produce are pixelated. 

**Steps to Reproduce**
- Create a scroll view or recycler view with content that is 3 or 4 times the length of a screen
- Configure paparazzi to use `renderingMode = SessionParams.RenderingMode.V_SCROLL`

**Expected behavior**
A clear images that are not pixelated

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: mac OS Monterey 12.1
- Compile SDK: 21
- Gradle Version: 7.4.2
- Android Gradle Plugin Version: 7.1.3

**Screenshots**

![org sharethemeal android view dashboard_DashboardScreenShotTest_dashboardScreen SAMSUNG_GALAXY_S10,en_GB](https://user-images.githubusercontent.com/898078/177008959-c4550e36-353c-4847-a767-049d165b05ca.png)

**Comment by fcduarte** [comment] 2022-07-27 05:26
Interesting! This is reproducible by changing line 24 of `paparazzi-gradle-plugin/src/test/projects/verify-rendering-modes/src/test/java/app/cash/paparazzi/plugin/test/RenderingModesTest.kt` to `(0..25)` from `(0..2)`.

**Comment by fcduarte** [comment] 2022-07-27 05:53
Found it, this is due to every screenshot to be limited to a 1000px, either width or height: https://github.com/cashapp/paparazzi/blob/eb60debfd74975c8dd6b4a240f1c81c09dfd689e/paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt#L93

Current implementation won't give you pixel perfect snapshots, I don't have context if this is intended. @jrodbx @luis-cortes any extra thoughts here? Does it make sense to implement a parameter like `createPixelPerfectSnapshot: Boolean` and then let library consumers pass it to their tests so they have the actual full not scaled image?

**Comment by fcduarte** [comment] 2022-07-28 18:06
Hi @sdoward, we discussed internally. Screenshots are limited to avoid the repo size to grow exponentially (if you use git LFS) and for making the HTML report easier to visualize. Could you share what's your use case for having an screenshot size closer to original? Thanks!

**Comment by brudaswen** [comment] 2022-07-29 08:24
Hacky workaround that might help you while the maxSie is not configurable:
```kotlin
    @Before
    fun initMaxImageSize() {
        maxImageSize?.let {
            Paparazzi::class.java.declaredFields.firstOrNull {
                it.name == "THUMBNAIL_SIZE"
            }?.let {
                it.isAccessible = true
                it.set(paparazzi, maxImageSize)
            }
        }
    }
```

**Comment by sdoward** [comment] 2022-07-31 14:24
@fcduarte thanks for the update. I would like to challenge the reasons that you mentioned...

**- repo size:** This should be the responsibility of the maintainer of the given repo rather than the responsibility of paparazzi
**- HTML report:** It should be easy enough to downscale the images when generating the report. Also Paparazzis main use case is for testing rather than render html pages

I feel like it would be great to set a default as 1000px for those reasons but limiting the functionality doesn't make much sense.

If a consumer of the lib wants a 5000px screenshot then I feel it should be allowed and they have to deal with the consequences, wether that be a big repo, poor html rendering or something else.


**My Use Case**

As you can see in the screenshot I posted... we have dashboard like feature. We want to write a test that includes all of the items that can potentially be displayed in the dashboard. This turns out to be much bigger than the device screen. 

Technically we could write separate tests and separate the items. However this adds unnecessary complexity into our work flow (we have designers review the recorded images during PR stage).

**Comment by fcduarte** [comment] 2022-08-01 13:56
@sdoward thanks for detailed explanation. I imagined it was for verification with designers ;) 

We'll have to discuss it internally to consider this as a feature enhancement. As always, PRs are welcome!

**Comment by fcduarte** [comment] 2022-08-01 17:45
I did a small refactoring at #526 so that in the future we want to handle scaled/non-scaled images we have only one source.

**Comment by sdoward** [comment] 2022-08-13 11:58
@fcduarte as you suggested: I opened up a PR. I am looking forward to feedback on it

**Comment by meesec** [comment] 2022-11-03 18:01
any chance we can still get this into 1.2? really looking forward to this 🤞

**Comment by joharei** [comment] 2022-12-06 15:14
My use case is that I use Paparazzi to generate screenshots for Play Store, and tablet screenshots need to be minimum 1080 px in each dimension.

**Comment by awaresiel** [comment] 2023-01-11 10:55
> Hacky workaround that might help you while the maxSize is not configurable:
> 
> ```kotlin
>     val maxImageSize = 2_000
> 
>     @Before
>     fun initMaxImageSize() {
>         maxImageSize?.let {
>             Paparazzi::class.java.declaredFields.firstOrNull {
>                 it.name == "THUMBNAIL_SIZE"
>             }?.let {
>                 it.isAccessible = true
>                 it.set(paparazzi, maxImageSize)
>             }
>         }
>     }
> ```

This wont work anymore, and also sometimes compose screenshot taken is partially white when using the V_SCROLL.

**Comment by SebastianIRodriguez** [comment] 2023-06-23 22:24
> My use case is that I use Paparazzi to generate screenshots for Play Store, and tablet screenshots need to be minimum 1080 px in each dimension.

I have the same use case, this feature would be really useful for generating this images.

**Comment by redwarp** [comment] 2023-09-05 10:28
Same here, Paparazzi looks like an amazing tool to automate screenshots, but the scaling makes it impossible.
@fcduarte I think your small refactoring pretty much made it impossible to override this behaviour by reflection (well, really hard, without using stuff like powermock or the like)

**Comment by mikolajdemkowww** [comment] 2024-02-06 07:54
@fcduarte   @jrodbx  are there any blockers to push forward PR in review?

**Comment by emuguy1** [comment] 2024-03-21 08:10
Is there any progress as I kind of really need this feature to automate the screenshot generation for the Play Store

**Comment by oldergod** [comment] 2024-06-04 15:36
Fixed by https://github.com/cashapp/paparazzi/pull/1382

**Closed** 2024-06-04 18:04 UTC
