### ISSUE TITLE
[Proposal] Fail tests when screenshots do not match and there needs to be different task to generate html report workflow

### ISSUE THREAD

**Issue by kozaxinan** [cashapp/paparazzi#1365] opened 2024-03-30 09:16 UTC
- Tests of a module with snapshots should do verification when the test task runs. And fail if there is a change in snapshots.
- Instead of verifyPaparazzi, there would be reportPaparazzi that generates HTML reports for incremental changes.

Current task setup
```mermaid
graph LR;
testDebugUnitTest--No paparazzi check--->Generate-HTML-Report;
verifyPaparazzi--Just Paparazzi--->Verification;
```

Suggestion
```mermaid
graph LR;
testDebugUnitTest--All tests including Paparazzi --->Verification;
reportPaparazzi--Generate Html Report--->Report;
verifyPaparazzi-->Deprecated;
```

While working on the cache issue reported in https://github.com/cashapp/paparazzi/issues/1334, we decided to change the test setup for report and verification for our setup. How likely could the following change be applied in the paparazzi library? I know it can affect backward compatibility and expectations of people already using the paparazzi.

**Comment by jrodbx** [comment] 2024-04-01 03:46
Duplicate of https://github.com/cashapp/paparazzi/pull/421.

**Closed by jrodbx** 2024-04-01 03:46 UTC
Labels: enhancement
