### ISSUE TITLE
Cache compatibility

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [cashapp/paparazzi#957] opened 2023-06-25 17:59 UTC
**Description**
Paparazzi is being rerun, and it forces other tests unrelated to Paparazzi to be rerun.

Some picks from a Gradle scan:

```
Cache key	c87bbc860acf8c09e16eb29226a9eef1	
Not cacheable	Overlapping outputs: Gradle does not know how file 'build\reports\paparazzi\videos' was created (output property '$1'). Task output caching requires exclusive access to output paths to guarantee correctness (i.e. multiple tasks are not allowed to produce output in the same location).
```

```
Cache key	8b28e5b01d9888e000649ab25ba30891	
Not cacheable	Overlapping outputs: Gradle does not know how file 'build\reports\paparazzi\runs\20230625195214_bfbd78.js' was created (output property '$1'). Task output caching requires exclusive access to output paths to guarantee correctness (i.e. multiple tasks are not allowed to produce output in the same location).
```

**Steps to Reproduce**
On and Android project, rerun `build` task two times, the second time shouldn't rerun any test if all of them were passing.

**Expected behavior**
Tests shouldn't be rerun if they were passing

**Comment by tasomaniac** [comment] 2023-07-21 10:51
Is this a duplicate of #586 ?

**Comment by jrodbx** [comment] 2023-09-09 19:19
Will need to revisit #586 more closely to see if there are other cacheability issues; however, I have confirmed that https://github.com/cashapp/paparazzi/pull/1082 fixes this issue.

Why?  The build task runs both testDebug and testRelease, and the report from the 2nd run was overwriting the 1st, since the report dir hadn't been variant aware.

**Closed by jrodbx** 2023-09-09 19:19 UTC
Labels: bug

**Comment by qonto-android-team** [comment] 2024-01-23 14:13
I am still seeing this issue on the latest version 1.3.2

**Comment by ashley-figueira** [comment] 2024-01-23 14:14
I am still seeing this issue using Paparazzi 1.3.2

**Comment by JavierSegoviaCordoba** [comment] 2024-01-23 14:17
We are still seeing this problem. Steps to reproduce:

1. Run `./gradlew testReleaseUnitTest`
2. Run `./gradlew clean`
3. Run `./gradlew testReleaseUnitTest`

Trace:

```
Overlapping outputs: Gradle does not know how file 'src/test/snapshots/images' was created (output property '$2'). Task output caching requires exclusive access to output paths to guarantee correctness (i.e. multiple tasks are not allowed to produce output in the same location).
```

Before it was `output property '$1'` but now it is `output property '$2'`. I am not sure if it is the same property which was moved or a different one.
