### ISSUE TITLE
Gradle fail with plugins  id 'com.android.dynamic-feature'

### ISSUE THREAD

**Issue by juckrit** [cashapp/paparazzi#665] opened 2022-12-21 00:24 UTC
**Description**
It seems like incompatible with dynamic-feature
when add 
plugins {
    id 'com.android.dynamic-feature'
}

**Steps to Reproduce**
clone repo here [https://github.com/davidvavra/showkase-screenshot-tests](url)
and then add plugins
id 'com.android.dynamic-feature'
in build.gradle(:feature)

**Screenshots**
<img width="1440" alt="Screenshot 2565-12-21 at 07 23 37" src="https://user-images.githubusercontent.com/35564862/208792122-241ea59d-e4ee-470a-8f45-a8f9a2009a57.png">

**Comment by JakeWharton** [comment] 2022-12-21 00:36
Dupe of #260. Feature modules are closer to apps than libraries so probably related to #107 as well.

**Closed by JakeWharton** 2022-12-21 00:36 UTC
Labels: bug
