### ISSUE TITLE
`lateinit property sessionParamsBuilder has not been initialized` when using compileSdk 33

### ISSUE THREAD

**Issue by chrisbanes** [cashapp/paparazzi#486] opened 2022-07-06 08:11 UTC
I'm guessing that this might be due to a layoutlib incompatibility for compile sdk 33. SDK 32 works as expected.

```
kotlin.UninitializedPropertyAccessException: lateinit property sessionParamsBuilder has not been initialized
	at app.cash.paparazzi.Paparazzi$Companion.getSessionParamsBuilder$paparazzi(Paparazzi.kt:612)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:161)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:122)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at com.twitter.test.runner.TwitterTestRunner$1.schedule(TwitterTestRunner.java:61)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
```

**Additional information:**
- Paparazzi Version: 1.0.0
- Compile SDK: 33
- Gradle Version: 7.4.2
- Android Gradle Plugin Version: 7.2.1

**Comment by chrisbanes** [comment] 2022-07-06 10:07
Digging into this a bit more. The root issue seems to be the following:

```
java.lang.IllegalArgumentException: value of system property 'ro.build.version.known_codenames' is longer than 91 characters: Base,Base11,Cupcake,Donut,Eclair,Eclair01,EclairMr1,Froyo,Gingerbread,GingerbreadMr1,Honeycomb,HoneycombMr1,HoneycombMr2,IceCreamSandwich,IceCreamSandwichMr1,JellyBean,JellyBeanMr1,JellyBeanMr2,Kitkat,KitkatWatch,Lollipop,LollipopMr1,M,N,NMr1,O,OMr1,P,Q,R,S,Sv2,Tiramisu
	at android.os.SystemProperties.set(SystemProperties.java:229)
	at com.android.layoutlib.bridge.Bridge.setSystemProperties(Bridge.java:319)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.android.layoutlib.bridge.Bridge.loadNativeLibraries(Bridge.java:720)
```

`SystemProperties` was updated in API 33 ([commit](https://cs.android.com/android/_/android/platform/frameworks/base/+/069f22cf0c23a25a0eeb0967a0f3589206881e18)) to support RO keys + values of any length. I tried updating to the Chipmunk layoutlib SHA but that has the same issue (I assume that we need Dolphin or EE).

For now I'm going to create a workaround by truncating each version to their letters and numbers. That will bring the value back down under 91 hopefully.

**Comment by eboudrant** [comment] 2022-07-12 06:17
We have a similar issue but we're using `compileSdk 31`, it happens intermittently in our CI builds (linux) but not on local builds, same stack : 
```
kotlin.UninitializedPropertyAccessException: lateinit property sessionParamsBuilder has not been initialized
	at app.cash.paparazzi.Paparazzi$Companion.getSessionParamsBuilder$paparazzi(Paparazzi.kt:612)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:161)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:122)
```

**Comment by chrisbanes** [comment] 2022-07-12 09:55
This stack trace seems to happen whenever there's any crashes in layoutlib's setup. The issue you're seeing may not be the same root cause as what I fixed in #487

**Comment by eboudrant** [comment] 2022-07-12 16:35
I see, I think our issue could be caused by #489, sometime in CI I see the `lateinit property sessionParamsBuilder has not been initialized` stack, sometime I see the `Layoutlib Bridge initialization failed` stack.

**Comment by jrodbx** [comment] 2022-07-30 02:44
Closing as resolved, per comment in https://github.com/cashapp/paparazzi/pull/487#issuecomment-1195584088

**Closed by jrodbx** 2022-07-30 02:44 UTC

**Comment by hlandim** [comment] 2023-01-20 09:55
> Digging into this a bit more. The root issue seems to be the following:
> 
> ```
> java.lang.IllegalArgumentException: value of system property 'ro.build.version.known_codenames' is longer than 91 characters: Base,Base11,Cupcake,Donut,Eclair,Eclair01,EclairMr1,Froyo,Gingerbread,GingerbreadMr1,Honeycomb,HoneycombMr1,HoneycombMr2,IceCreamSandwich,IceCreamSandwichMr1,JellyBean,JellyBeanMr1,JellyBeanMr2,Kitkat,KitkatWatch,Lollipop,LollipopMr1,M,N,NMr1,O,OMr1,P,Q,R,S,Sv2,Tiramisu
> 	at android.os.SystemProperties.set(SystemProperties.java:229)
> 	at com.android.layoutlib.bridge.Bridge.setSystemProperties(Bridge.java:319)
> 	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
> 	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
> 	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
> 	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
> 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
> 	at java.base/java.lang.Runtime.load0(Runtime.java:768)
> 	at java.base/java.lang.System.load(System.java:1837)
> 	at com.android.layoutlib.bridge.Bridge.loadNativeLibraries(Bridge.java:720)
> ```
> 
> `SystemProperties` was updated in API 33 ([commit](https://cs.android.com/android/_/android/platform/frameworks/base/+/069f22cf0c23a25a0eeb0967a0f3589206881e18)) to support RO keys + values of any length. I tried updating to the Chipmunk layoutlib SHA but that has the same issue (I assume that we need Dolphin or EE).
> 
> For now I'm going to create a workaround by truncating each version to their letters and numbers. That will bring the value back down under 91 hopefully.

I'm still having this issue with the latest 1.2.0 version.

**Comment by JakeWharton** [comment] 2023-01-20 12:36
Open a new issue with a minimally reproducing sample please.

**Comment by hlandim** [comment] 2023-01-24 10:08
> Open a new issue with a minimally reproducing sample please.

Sorry, It was my mistake, although I had updated the version, the gradle cache was making me keep using the old version.
after cleaning the cache and tried again, it worked, thanks.

**Comment by TWiStErRob** [comment] 2023-01-24 13:39
@hlandim do you know what part was keeping the old version? Because that means there's a bug somewhere in someone's code. If you change a version, Gradle must not use a cached version.
