### ISSUE TITLE
Snapshot missing app.cash.paparazzi:paparazzi:1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by saurabhkpatel** [cashapp/paparazzi#404] opened 2022-04-01 16:49 UTC
Trying the snapshot version from here: https://oss.sonatype.org/content/repositories/snapshots/app/cash/paparazzi/ but it doesn't full the `app.cash.paparazzi:paparazzi:1.0.0-SNAPSHOT` dependency and it doesn't resolve the paparazzi plugin classes.

Is this expected behavior? My setup looks like the below:

root
  - build.gradle
  - module_1
       - build.gradle

**root build.gradle looks like this:**
```
buildscript {
    ext {
        compose_version = '1.1.1'
    }
    repositories {
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
    dependencies {
        classpath "app.cash.paparazzi:paparazzi-gradle-plugin:1.0.0-SNAPSHOT"
    }
}
// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '7.1.2' apply false
    id 'com.android.library' version '7.1.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.10' apply false
}

....
....

```
**module_1 build.gradle**

```
plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'app.cash.paparazzi'
}
....
....
```

Error:

Failed to resolve: app.cash.paparazzi:paparazzi:1.0.0-SNAPSHOT
Show in Project Structure dialog
Affected Modules: coreui

![image](https://user-images.githubusercontent.com/1188367/161306942-a7958049-a2e5-4c6f-8e38-d07bad9b3499.png)

**Comment by jrodbx** [comment] 2022-04-01 17:09
I think the issue is you'll need to also add a similar repositories block to your subprojects either directly in their build.gradle scripts or in a root script subprojects block.

**Comment by saurabhkpatel** [comment] 2022-04-03 22:20
I tried that already but it's not working. You can try this repo: https://github.com/saurabhkpatel/composedemo and try to do Gradle sync and it will throw the error.

**Comment by jrodbx** [comment] 2022-04-03 23:04
Thanks for the repro project; it was helpful!

So it looks like you added a buildscript/repositories block in coreui/build.gradle in [this commit](https://github.com/saurabhkpatel/composedemo/commit/34e1365abe7aedbe5fd17aa757533bbfffd03164), which is slightly different from what I was suggesting:

```
//buildscript {
//    ext {
//        compose_version = '1.1.1'
//    }
//    repositories {
//        maven {
//            url 'https://oss.sonatype.org/content/repositories/snapshots/'
//        }
//    }
//    dependencies {
//        classpath "app.cash.paparazzi:paparazzi-gradle-plugin:1.0.0-SNAPSHOT"
//    }
//}

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'app.cash.paparazzi'
}

// this is needed so that the plugin can find the actual test library
repositories {
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/' 
    }
}

```

However, this will fail as well, since you are using pluginManagement and dependencyResolutionManagement blocks.

Therefore, the solution for this fun Gradle case is to add the following to our settings.gradle:
<img width="705" alt="Screen Shot 2022-04-03 at 7 03 49 PM" src="https://user-images.githubusercontent.com/1868149/161452629-23cf2923-a190-4acc-b832-63394e08c574.png">

And then syncing/building should work!

**Comment by jrodbx** [comment] 2022-04-04 22:35
Closing as this is a Gradle configuration issue and a working solution has been proposed.

**Closed by jrodbx** 2022-04-04 22:35 UTC

**Comment by saurabhkpatel** [comment] 2022-04-06 02:47
Wow, too many places to put repositories !! :)
thanks for your help
