### ISSUE TITLE
Contributions execute CI twice

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#572] opened 2022-09-08 21:54 UTC
**Description**

Mine: https://github.com/TWiStErRob/paparazzi/actions/runs/3018338316
PR: https://github.com/cashapp/paparazzi/actions/runs/3018338528

**Steps to Reproduce**
I had to fork the repo and when I push to a branch it executes CI, and it also executes on the PR.

**Expected behavior**
No CI on fork, because it wastes GHA hours.

**Comment by JakeWharton** [comment] 2022-09-08 23:34
Push let's you test branches before PRs. A very useful workflow.

**Comment by jrodbx** [comment] 2022-09-09 02:03
As Jake said, that's by design -- build on push.  If there's a way to detect whether an opened PR has already been built, I'm game for a contribution; otherwise, I'm indifferent on GHA hours.

**Comment by JakeWharton** [comment] 2022-09-09 02:18
$0 * 2 is still $0!

**Comment by TWiStErRob** [comment] 2022-09-09 08:50
Yes, @JakeWharton, but that 2 has an upper bound, there's only 2000 hours and there are Macs in the workflow which uses 10x minutes. https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes
I have my own active projects where I use those hours (a lot of them).

This is the theory anyway... I checked my usage report and it's empty for the last 180 days... which sounds like a problem, because I have CI jobs using 2 hours per commit. 😅

**Comment by jrodbx** [comment] 2022-09-14 17:49
Closing as wontfix, but happy to accept an PR per https://github.com/cashapp/paparazzi/issues/572#issuecomment-1241414832 and https://github.com/cashapp/paparazzi/issues/572#issuecomment-1241993438

**Closed by jrodbx** 2022-09-14 17:49 UTC
Labels: bug
