### ISSUE TITLE
Use layoutlib tarball in place of a Git clone

### ISSUE THREAD

**Issue by msfjarvis** [cashapp/paparazzi#485] opened 2022-07-05 15:16 UTC
Paparazzi currently clones the entire [layoutlib Git repo](https://android.googlesource.com/platform/prebuilts/studio/layoutlib) to re-publish `layoutlib` and the native artifacts. This is very wasteful, when we have the option to simply download a GZipped tarball instead. You can see the difference in network usage and on-disk size:

```
➜ curl -Lo layoutlib.tar.gz https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+archive/573f070.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  168M    0  168M    0     0  4820k      0 --:--:--  0:00:35 --:--:-- 3095k
➜ git clone https://android.googlesource.com/platform/prebuilts/studio/layoutlib
Cloning into 'layoutlib'...
remote: Total 29056 (delta 10456), reused 29056 (delta 10456)
Receiving objects: 100% (29056/29056), 8.95 GiB | 11.96 MiB/s, done.
Resolving deltas: 100% (10456/10456), done.

➜ diskus layoutlib.tar.gz 
177.10 MB (177,098,752 bytes)
➜ diskus layoutlib/
9.62 GB (9,616,052,224 bytes)
```

Apache's [commons-compress](https://commons.apache.org/proper/commons-compress/) library can extract GZIP archives very easily, and we can leverage this to download just the tarball and sidestep the huge disk and network penalty of the Git clone.

I'm happy to send a PR for this once the proposal is accepted.

**Comment by chrisbanes** [comment] 2022-07-26 08:32
I'm not a maintainer, but I think this is definitely worth a PR!

**Comment by jrodbx** [comment] 2022-07-26 14:42
Duplicate of #314.

Eventually, we want to build layoutlib from source, so I'm afraid the git clone will remain to support this future use case.

**Closed by jrodbx** 2022-07-26 14:42 UTC
