### ISSUE TITLE
Composable map

### ISSUE THREAD

**Issue by adonislapin** [cashapp/paparazzi#735] opened 2023-03-14 18:05 UTC
Im using the new google composable maps in my app, everything is working good when I run normally, the issue comes when I try to make some test(snapshots) using the google map, but I have an exception. I added the lines that the logs says but the exception continue.

I added to my manifest file
<application>
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="${MAPS_API_KEY}" />

Expected result:
Generate the snapshots using the composable google maps

- Paparazzi Version: 1.2.0
- OS: Mac OS 13.2.1
- Compile SDK:  33
- Gradle Version:  gradle-7.4
- Android Gradle Plugin Version: 7.2

Logs

com.google.android.gms.common.GooglePlayServicesMissingManifestValueException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
	at app//com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(com.google.android.gms:play-services-basement@@18.0.0:8)
	at app//com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(com.google.android.gms:play-services-base@@18.0.1:2)
	at app//com.google.android.gms.maps.internal.zzcb.zza(com.google.android.gms:play-services-maps@@18.1.0:3)
	at app//com.google.android.gms.maps.MapsInitializer.initialize(com.google.android.gms:play-services-maps@@18.1.0:4)
	at app//com.google.android.gms.maps.MapsInitializer.initialize(com.google.android.gms:play-services-maps@@18.1.0:1)
	at app//com.google.android.gms.maps.zzah.zzb(com.google.android.gms:play-services-maps@@18.1.0:2)
	at app//com.google.android.gms.maps.zzah.createDelegate(com.google.android.gms:play-services-maps@@18.1.0:1)
	at app//com.google.android.gms.dynamic.DeferredLifecycleHelper.zaf(com.google.android.gms:play-services-base@@18.0.1:6)
	at app//com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@18.0.1:1)
	at app//com.google.android.gms.maps.MapView.onCreate(com.google.android.gms:play-services-maps@@18.1.0:4)
	at app//com.google.maps.android.compose.GoogleMapKt.lifecycleObserver$lambda-11(GoogleMap.kt:185)
	at app//androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
	at app//androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
	at app//androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
	at app//androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:210)
	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
	at app//androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
	at app//android.view.View.dispatchAttachedToWindow(View.java:21291)
	at app//android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
	at app//android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at app//android.view.ViewGroup.addViewInner(ViewGroup.java:5291)
	at app//android.view.ViewGroup.addView(ViewGroup.java:5077)
	at app//android.view.ViewGroup.addView(ViewGroup.java:5017)
	at app//android.view.ViewGroup.addView(ViewGroup.java:4989)
	at app//app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:303)
	at app//app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:200)
	at app//app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:199)
	at app//app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:195)
	at app//app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:191)
	at app//com.hilton.mobile.fractal.ComponentSnapshotTest.runComponentTest(ComponentSnapshotTest.kt:59)
	at app//com.hilton.mobile.fractal.MapThumbnailSnapshotTest.mapThumbnailTest(MapThumbnailSnapshotTest.kt:14)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:118)
	at app//com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:420)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

**Comment by BrianGardnerAtl** [comment] 2023-03-23 18:37
Paparazzi doesn't support the maps unfortunately and with the added complexity I'm not sure if it's feasible at this time. A workaround you can do is to add this around your composable invocations in your tests:

```
    CompositionLocalProvider(LocalInspectionMode provides true) {
        // composable here
    }
```

This will force the `GoogleMap` composable to short circuit and return an empty box. It's not ideal but it should allow you to snapshot test any other UI elements you display alongside the map.

**Comment by jrodbx** [comment] 2023-03-25 02:04
Does @Preview in Android Studio work with Google Maps?  According to https://github.com/cashapp/paparazzi/issues/709, this should be possible.  That issue still fails, but not with a missing api key like yours does.

**Comment by hlandim** [comment] 2023-04-11 21:34
The preview is working fine here,
my problem is :

Paparazzi: `1.2.0`
google.android.maps-compose: `2.11.4`
google.android.play-services-maps: `18.1.0`

```
java.lang.NullPointerException
	at com.google.android.gms.common.internal.zzag.zzc(com.google.android.gms:play-services-basement@@18.0.0:5)
	at com.google.android.gms.common.internal.zzag.zza(com.google.android.gms:play-services-basement@@18.0.0:1)
	at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(com.google.android.gms:play-services-basement@@18.0.0:7)
...
java.lang.IllegalStateException: layout state is not idle before measure starts
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1081)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:342)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1173)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:307)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(MeasureAndLayoutDelegate.kt:479)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.recurseRemeasure(MeasureAndLayoutDelegate.kt:357)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureOnly(MeasureAndLayoutDelegate.kt:348)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt:854)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:302)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:289)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.widget.RelativeLayout.measureChild(RelativeLayout.java:696)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:499)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:26358)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:26322)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:660)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.doLayout(RenderSessionImpl.java:413)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:556)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:456)
	at app.cash.paparazzi.Paparazzi$takeSnapshots$1$2.invoke(Paparazzi.kt:307)z

```

**Comment by hlandim** [comment] 2023-04-12 12:28
I managed to overcome it by mocking the `LocalInspectionMode` with mockk
```
        paparazzi.snapshot {
            mockkStatic("androidx.compose.ui.platform.InspectionModeKt")
            every { LocalInspectionMode } returns staticCompositionLocalOf { true }
            MyComposableScreen()
        }
```
As google maps is not using the maps when it is on PreviewMode.

### GoogleMap.kt :
```
    // When in preview, early return a Box with the received modifier preserving layout
    if (LocalInspectionMode.current) {
        Box(modifier = modifier)
        return
    }

```

**Comment by saket** [comment] 2023-04-19 17:11
FWIW you don't need to mock composition locals. 

```kotlin
paparazzi.snapshot {
  CompositionLocalProvider(LocalInspectionMode provides true) {
    MyComposableScreen()
  }
}
```

**Comment by Sdssourcing** [comment] 2023-04-21 06:05
#

**Comment by jrodbx** [comment] 2023-08-24 18:55
Closed as duplicate of https://github.com/cashapp/paparazzi/issues/709, relates to https://github.com/cashapp/paparazzi/issues/508.

**Closed by jrodbx** 2023-08-24 18:55 UTC
Labels: bug
