### ISSUE TITLE
When I run the tests I am getting the Unknown field type in R class: class error

### ISSUE THREAD

**Issue by jd-alexander** [cashapp/paparazzi#732] opened 2023-03-08 22:47 UTC
**Description**

I have integrated Paparazzi into a repository at work and I am getting this error: 
```
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
Mar 08, 2023 5:42:02 PM app.cash.paparazzi.internal.PaparazziLogger error
SEVERE: Unknown field type in R class: class [Z
```
**Steps to Reproduce**

I am working on seeing if I can reproduce this in a sample repository. 

**Expected behavior**
The paparazzi test runs as expected. 

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: MacOS Monterey 12.6
- Compile SDK: 22
- Gradle Version: 7.6
- Android Gradle Plugin Version: 7.4.1

**Screenshots**

**Comment by JakeWharton** [comment] 2023-03-08 23:13
That's a boolean array. Somehow you made a boolean array.

**Comment by TWiStErRob** [comment] 2023-03-09 10:10
@jd-alexander I think you might want to look at your `build\intermediates\compile_r_class_jar\debug\R.jar` with a decompiler and see what's up.

Also opened https://github.com/cashapp/paparazzi/pull/733 to improve the error message, because clearly the current one doesn't give us enough info, while it's easily available at the log line.

**Comment by castorflex** [comment] 2023-03-15 12:44
Hey, I'm able to reproduce that issue and debug a bit with a breakpoint in PaparazziCallback. It seems related to jacoco on my side.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1364129/225291780-99c28953-64f0-44d8-9d7e-6db376e82a02.png">

**Comment by jrodbx** [comment] 2023-03-25 01:59
@jd-alexander have you been able to set up a repro?

**Comment by jd-alexander** [comment] 2023-03-25 04:06
> @jd-alexander have you been able to set up a repro?

Hey John, I haven't been able to reproduce. I will give it another try next week.

**Comment by ashley-figueira** [comment] 2023-03-27 16:23
To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.

Maybe we should add a check before logging if the field is synthetic?!

**Comment by ashley-figueira** [comment] 2023-03-30 08:48
@jd-alexander As a workaround, if you remove the JaCoCo plugin when running your screenshot tests, you should not see those logs. You can follow this [tutorial](https://poetengineer.postach.io/post/how-to-conditionally-enable-disable-jacoco-in-gradle-build) to remove the JaCoCo plugin condionally.

**Comment by jrodbx** [comment] 2023-03-30 15:44
I think a hidden gem in that tip is that it seems one can exclude R classes from jacoco instrumentation (which makes sense to me, why test R coverage?)

```
task jacocoTestReport(type: JacocoReport, dependsOn: ['testDebugUnitTest']) {

    def fileFilter = ['**/R.class',
    ...
}
```

**Comment by jrodbx** [comment] 2023-06-10 02:01
Closing since this appears to be a user configuration issue.  Please refile with a sample.

**Closed by jrodbx** 2023-06-10 02:01 UTC
Labels: bug, waiting on user

**Comment by matejdro** [comment] 2023-12-11 12:21
I can reproduce this by just running `/gradlew :sample:recordPaparazziDebug` on https://github.com/cashapp/paparazzi/tree/d146c9739e3f434ef0c196061ce66e26ba20bff5 (latest master as of writing this)

```
> Task :sample:testDebugUnitTest

app.cash.paparazzi.sample.ComposeA11yTest > compositeItems STANDARD_ERROR
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$array.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$bool.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$color.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$dimen.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$drawable.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$integer.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$layout.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$plurals.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] app.cash.paparazzi.sample.R$string.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.activity.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.compose.ui.R$color.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.compose.ui.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.compose.ui.R$string.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.compose.ui.R$style.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.lifecycle.viewmodel.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$attr.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$color.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$dimen.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$drawable.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$integer.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$layout.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$string.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$style.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.autofill.R$styleable.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.customview.poolingcontainer.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$attr.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$color.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$dimen.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$drawable.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$integer.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$layout.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$string.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$style.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.core.R$styleable.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.lifecycle.runtime.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.savedstate.R$id.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.PaparazziLogger error
    SEVERE: Unknown type (class [Z) in R class field: private static transient boolean[] androidx.startup.R$string.$jacocoData
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 24
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 34
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 41
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 47
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 53
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 59
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 65
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 70
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 75
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 80
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 85
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 91
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 95
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 100
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 105
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 109
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 113
    Dec 11, 2023 1:19:05 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    WARNING: Unrecognized tag name "java-symbol" at /home/matejd/Android/Sdk/platforms/android-33/data/res/values/config_telephony.xml line 121
    Dec 11, 2023 1:19:06 PM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
    INFO: Settings [3]: Can't get key animator_duration_scale from content://settings/global
```

**Comment by TWiStErRob** [comment] 2023-12-11 19:28
Ref the line that added this: https://github.com/cashapp/paparazzi/pull/1167#discussion_r1421728149

**Comment by larryng** [comment] 2024-01-11 16:38
FWIW this issue came onto our radar because the log spam dramatically increases the size of JUnit XML output files, causing timeouts in CI because parsing the files was taking so long. So, although it's currently non-blocking, it'd be nice to ship [the fix](https://github.com/cashapp/paparazzi/pull/1223) sooner rather than later 🙂.
