### ISSUE TITLE
Does not work with Butterknife

### ISSUE THREAD

**Issue by drobekkrzysztof** [cashapp/paparazzi#1197] opened 2023-12-21 08:11 UTC
**Description**
Fails when run on a library module with butterknife plugin, with the following message:

```
java.lang.ClassFormatError: Duplicate field name "BodyCenter_android_breakStrategy" with signature "I" in class file redacted/ui/R$styleable
	at java.base/java.lang.Class.getDeclaredClasses0(Native Method)
	at java.base/java.lang.Class.getDeclaredClasses(Unknown Source)
	at app.cash.paparazzi.internal.PaparazziCallback.initResources(PaparazziCallback.kt:60)
	at app.cash.paparazzi.Paparazzi.prepare(Paparazzi.kt:152)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:124)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at com.google.testing.junit.testparameterinjector.PluggableTestRunner$ContextMethodRule$1.evaluate(PluggableTestRunner.java:420)
```

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: MacOS Sonoma 14.1.1
- Compile SDK: 34
- Gradle Version: 8.0
- Android Gradle Plugin Version: 8.1.4

**Comment by jrodbx** [comment] 2024-05-24 13:55
Duplicate of #481?  Have you tried the workaround here? https://github.com/cashapp/paparazzi/issues/481#issuecomment-1386484783.  Also, consider migrating to ViewBinding as Butterknife is [now deprecated](https://github.com/JakeWharton/butterknife?tab=readme-ov-file#butter-knife).

**Closed by jrodbx** 2024-05-24 13:55 UTC
Labels: bug
