### ISSUE TITLE
Tests pass successfully even when a View fails to render itself

### ISSUE THREAD

**Issue by saket** [cashapp/paparazzi#423] opened 2022-05-05 05:07 UTC
When a View throws an exception during its measurement/layout, paparazzi swallows the error and generates an empty image. Could paparazzi bubble up the exception instead so that tests are shown as failures?

**Comment by mshafrir-stripe** [comment] 2022-05-13 20:25
I'm also seeing this in `0.9.3`. For example, I see the following exception thrown in a test, but Paparazzi doesn't flag the test as a failure.

```
    Caused by: java.lang.NullPointerException
        at android.graphics.Typeface.createFromResources(Typeface.java:251)
        at android.graphics.Typeface_Delegate.createFromDisk(Typeface_Delegate.java:97)
        at com.android.layoutlib.bridge.impl.ResourceHelper.getFont(ResourceHelper.java:455)
        at com.android.layoutlib.bridge.impl.ResourceHelper.getFont(ResourceHelper.java:467)
        at android.content.res.BridgeTypedArray.getFont(BridgeTypedArray.java:720)
        at android.widget.TextView.readTextAppearance(TextView.java:4020)
        at android.widget.TextView.<init>(TextView.java:1089)
        at android.widget.EditText.<init>(EditText.java:87)
        at android.widget.EditText.<init>(EditText.java:83)
        at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:93)
        at com.google.android.material.textfield.TextInputEditText.<init>(TextInputEditText.java:64)
        at com.google.android.material.textfield.TextInputEditText.<init>(TextInputEditText.java:59)
        ... 90 more
```

**Comment by jrodbx** [comment] 2022-05-25 22:19
Duplicate of #222

**Closed** 2022-05-25 22:21 UTC
