### ISSUE TITLE
Running an individual test or via pattern

### ISSUE THREAD

**Issue by ben-gooding-sky** [cashapp/paparazzi#1154] opened 2023-11-01 12:31 UTC
We have a large suite of tests and it takes too long to run them all if I want to just update 1 image, or make a few small tweaks.

Something like `--filter {regexMatcher}` or `--tests {pathToTest}`

**Comment by TWiStErRob** [comment] 2023-11-01 14:35
Does [`--tests`](https://docs.gradle.org/current/userguide/java_testing.html#simple_name_pattern) not work? `testDebugUnitTest` should be of type `com.android.build.gradle.tasks.factory.AndroidUnitTest` which extends the built-in `Test` task.

This means the following should work (in theory):
```
gradlew recordPaparazziDebug --tests com.example.MyTest.testFoo
```

**Comment by TWiStErRob** [comment] 2023-11-01 14:38
Hmm, seems I was wrong, it doesn't "just work", but good news should be that this is a duplicate of #181 which was implemented in #216.

**Comment by ben-gooding-sky** [comment] 2023-11-02 09:26
Oh yeah I think it does work I just used a whitespace rather than `=` for `--tests`

Thanks for looking into it

It would be helpful to put this on the main `readme` as it's very common!

**Comment by jrodbx** [comment] 2023-12-10 00:51
Closing as this is a Gradle not Paparazzi issue.  As @TWiStErRob mentions, we provided this in #216 using the same mechanism as Gradle.  

running both:
```
./gradlew sample:testDebug --tests *HelloComposeTest
```
and
```
./gradlew sample:testDebug --tests=*HelloComposeTest
```
works for me locally.

**Closed by jrodbx** 2023-12-10 00:51 UTC
Labels: enhancement
