### ISSUE TITLE
Emojis and new line not similar to Android Studio Preview in TextView

### ISSUE THREAD

**Issue by jk-groww** [cashapp/paparazzi#698] opened 2023-01-23 10:48 UTC
**Description**
When special characters are used eg: `\n` `\uD83D\uDE00` `\uD83D\uDC4C`. The snapshot looks different from Android Studio.

**Expected behavior**
Should render special characters.

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: mac OS
- Compile SDK: 32
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.4.0

**Screenshots**
| In Android Studio | With Paparazzi |
| -- | -- |
| <img width="264" alt="Screenshot 2023-01-23 at 4 02 11 PM" src="https://user-images.githubusercontent.com/113583580/214020517-26759a8a-c40b-4370-8e92-81c06d48b7dc.png"> | <img width="320" alt="Screenshot 2023-01-23 at 4 11 08 PM" src="https://user-images.githubusercontent.com/113583580/214020645-3541d338-98db-4442-9f21-c516ae528d34.png"> |

**Comment by jrodbx** [comment] 2023-01-25 22:42
While I haven't triaged this yet, feels related to a known resource parsing issue, alluded to in: https://github.com/cashapp/paparazzi/issues/634

**Comment by jrodbx** [comment] 2023-06-09 19:36
I can't reproduce this on latest Paparazzi, so I assume this was fixed as of Flamingo.  Can you confirm that 1.3.0 no longer shows this behavior?

**Comment by jrodbx** [comment] 2023-07-06 05:51
This is fixed on master when enabling the new resource loading mechanism, tracked in https://github.com/cashapp/paparazzi/issues/524.

This might also be fixed using the old resource loading mechanism, courtesy of https://github.com/cashapp/paparazzi/issues/975.

**Closed by jrodbx** 2023-07-06 05:51 UTC
Labels: bug, waiting on user
