### ISSUE TITLE
Cannot record Paparazzi test due to UnsupportedOperationException

### ISSUE THREAD

**Issue by tassilo-posegga** [cashapp/paparazzi#979] opened 2023-07-04 18:56 UTC
**Description**
Since a couple of months my colleagues complained that they are not able to record any Paparazzi tests due to an exception which I couldn't reproduce at that time and we also couldn't spot any differences in setup. Now is the time where the same issue popped up on my machine:

```
StayLoggedInScreenTest > [isAccessible=false] > testLoadingStayLoggedInContent[isAccessible=false] FAILED
    java.lang.UnsupportedOperationException at null:-2
```
Here is the full stack trace:
https://pastebin.com/dv7uH5jg

**Steps to Reproduce**
Record any Paparazzi test using :recordPaparazzi gradle command

**Expected behavior**
No Exception :)

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: MacOS (M1) & Windows 11
- Compile SDK: 34
- Gradle Version: 8.1.1 (but was happening with 7.X as well)
- Android Gradle Plugin Version: 7.4.2

**Comment by TWiStErRob** [comment] 2023-07-05 07:49
Please try to upgrade to Paparazzi 1.3.0, as this has been considered fixed in #384.

Just to confirm: are you using Java 17 and jacoco?
If the answers are yes and you get it after upgrading to 1.3 too, then this is likely a duplicate of #955.

**Comment by tassilo-posegga** [comment] 2023-07-06 10:20
We couldn't upgrade to AGP 8.X yet - so we currently still run Java 11. We do have jacoco though
AFAIK we need to update AGP before upadting Paparazzi to 1.3.0

**Comment by TWiStErRob** [comment] 2023-07-06 10:54
I think it might be possible to 1.3.0 with AGP 7.4 on Gradle 7.6/8, because the AGP 8 bump happened late during Paparazzi 1.3, see the commits that happened after the bump: https://github.com/cashapp/paparazzi/compare/3d401cff34d0515507c857799c4996db1e16cd59...1.3.0, at a quick glance I don't see any breaking changes re AGP 7/8.

java target is still 11, so I think you can try this way:
 * update paparazzi 1.2.0 to 1.3.0
 * exclude transitive AGP dependencies on `buildscript > classpath` or `buildSrc`/included build that come from the `paparazzi-gradle-plugin` to prevent upgrading AGP too
 * define `android.nonTransitiveRClass` in `gradle.properties` explicitly to help paparazzi know the value (the default assumption changed in AGP 8)

**Comment by jrodbx** [comment] 2023-07-06 23:02
@tassilo-posegga do you have an anticipated timeline for AGP 8.x upgrade?  If not, I think this is covered by other issues, so I'm likely to close this.

**Comment by tassilo-posegga** [comment] 2023-07-10 10:03
Currently having open a migration branch for AGP 8 with Java 17
Also updates Paprazzi to 1.3.0 but still having the same issues

**Comment by jrodbx** [comment] 2023-07-12 05:32
If the upgrade to APG 8 + Java 17 still results in the same issue, I'd suggest:

1) reviewing the aforementioned issues to see if there are any comments/configurations that might be corresponding to your issue (e.g., not running Paparazzi tests in androidTest)
2) if nothing there, please provide a minimal repro/sample of the issue.  it's difficult to debug everyone's specific configuration otherwise.

**Comment by tinder-johnbuhanan** [comment] 2023-08-29 18:29
> exclude transitive AGP dependencies on buildscript > classpath or buildSrc/included build that come from the paparazzi-gradle-plugin to prevent upgrading AGP too

How do I do this?  I tried this with no luck:
<img width="478" alt="image" src="https://github.com/cashapp/paparazzi/assets/102559887/c92ea94d-80ea-48f2-bd9a-9d4473ceb718">

**Comment by TWiStErRob** [comment] 2023-08-29 19:22
That's what I meant, based on just this snippet, it should work, check with `gradlew buildEnvironment` what's the dep tree, there might be another plugin pulling it in. Exclude only works if there are no other dependencies doing the same thing, so it's more error-prone.

Also try this, probably a better way of expressing what we want here:
```gradle
buildscript { dependencies { constraints {
	add("classpath", buildLibs.androidPlugin) {
		version { strictly(requiredVersion) } // Enforces our version, regardless of what other plugins say.
		because("https://github.com/cashapp/paparazzi/issues/979#issuecomment-1623464219")
	}
	// Same for com.android.tools:sdk-common with version matching AGP.
} } }
```
Note that https://github.com/cashapp/paparazzi/issues/979#issuecomment-1623464219 is theory, I never tried it. Happy to help figure it out though. I would recommend moving this conversation to a [discussion](https://github.com/cashapp/paparazzi/discussions) if it doesn't work based on the above to keep this issue focused on the issue, not the workaround.

**Closed** 2023-12-09 15:51 UTC
Labels: bug, waiting on user
