### ISSUE TITLE
AsyncImage inside LazyColumn doesn't render

### ISSUE THREAD

**Issue by ben-gooding-sky** [cashapp/paparazzi#1087] opened 2023-09-14 10:03 UTC
**Description**
When putting an `AsyncImage` inside a `LazyColumn`, causes it not to paint.
It goes away if you put it in a regular `Column`

**Steps to Reproduce**
```
LazyColumn {
   items(listOf(1,2,3)) {
      AsyncImage(...)
   }
}
```

**Expected behavior**
Image gets rendered in snapshot

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: MacOS (Apple Silicon)
- Compile SDK:  17.0.7
- Gradle Version: 8.3
- Android Gradle Plugin Version:

**Comment by gamepro65** [comment] 2023-09-20 19:22
Is this referring to `coil.compose.AsyncImage`?

When Paparazzi takes a snapshot of a `ComposeView`, we first run a composition when attaching `ComposeView` to the hierarchy, then execute any pending `Handler` callbacks, and finally tell Layoutlib to take a snapshot which internally calls measure / draw.

If we look at [AsyncImagePainter](https://github.com/coil-kt/coil/blob/main/coil-compose-base/src/main/java/coil/compose/AsyncImagePainter.kt#L227), we see they update their internal painter with `Dispatchers.Main.immediate` which is backed by a `Handler`. In the case of `Column`, this call to `Dispatchers.Main.immediate` will be queued during that initial composition and will then run when we execute pending `Handler` callbacks.  However, with `LazyColumn` items are not composed until the measure pass so it can figure out how many items to render. In this case, unfortunately, we cannot force the `Handler` to execute any pending callbacks before drawing and so the Painter misses the first draw call. If you call the gif API with the same setup, I'd imagine the 2nd frame would show the image.

I'd suggest opening an issue with Coil to expose a configuration option for that `Dispatcher` so you can seed `Dispatchers.Unconfined` which will synchronously set the painter in time for the first draw.

**Comment by jrodbx** [comment] 2023-09-23 06:35
Closing as the issue is unrelated to Paparazzi

**Closed by jrodbx** 2023-09-23 06:35 UTC
Labels: bug
