### ISSUE TITLE
GIF verification support

### ISSUE THREAD

**Issue by sumitjat** [cashapp/paparazzi#978] opened 2023-07-04 07:13 UTC
I was checking _GIF verification_ support which is not there in library at the moment , but there seems to be multiple Merge request raised to support for [same](https://github.com/cashapp/paparazzi/pulls?q=is:pr+is:open++gif). Do we have any plan to Merge those ?

**Comment by iujames** [comment] 2023-09-21 18:28
This would be very useful for our project as well!

**Comment by jrodbx** [comment] 2024-01-17 22:06
Closing as duplicate of #496

**Closed by jrodbx** 2024-01-17 22:06 UTC
Labels: enhancement
