### ISSUE TITLE
Compatibility with JUnit 5

### ISSUE THREAD

**Issue by rulogarcillan** [cashapp/paparazzi#1215] opened 2024-01-10 12:14 UTC
Hello!!!

I would like to inquire about the status of Paparazzy's compatibility with JUnit 5. Are there any ongoing developments or future plans to make Paparazzy compatible with JUnit 5? This information would be valuable to the community of Android developers.

Regards

**Comment by jrodbx** [comment] 2024-01-10 12:38
duplicate of #282

**Closed by jrodbx** 2024-01-10 12:38 UTC
Labels: enhancement
