### ISSUE TITLE
HtmlToSpannedConverter.handleEndTag NullPointerException Paparazzi 1.2.0

### ISSUE THREAD

**Issue by tomkoptel** [cashapp/paparazzi#694] opened 2023-01-20 10:18 UTC
**Description**

An NPE exception is coming from `app.cash.paparazzi:layoutlib-native-jdk11:2022.1.1-beta4-f5f9f71` when the app tries to parse HTML using `HtmlCompat.fromHtml`.

```java
public static Spanned fromHtml(@NonNull String source, @FromHtmlFlags int flags) {
```

**Steps to Reproduce**
1. Open [the project](https://github.com/tomkoptel/paparazzi-htmlcompat-issue) in `Android Studio Electric Eel | 2022.1.1`
2. [Run the test](https://github.com/tomkoptel/paparazzi-htmlcompat-issue/blob/develop/mylibrary/src/test/java/com/example/mylibrary/MyPresenterSnapshotTest.kt#L9). 

**Expected behavior**
It is not crashing while parsing the HTML using `androidx.core.text.HtmlCompat`.

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: macOS Ventura 13.0
- Kotlin Compile SDK: 1.7.21
- Java Compile SDK: Zulu JDK 11
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.4.0

**Stacktrace**
```
java.lang.NullPointerException
	at android.text.HtmlToSpannedConverter.handleEndTag(Html.java:869)
	at android.text.HtmlToSpannedConverter.endElement(Html.java:1247)
	at org.ccil.cowan.tagsoup.Parser.pop(Parser.java:737)
	at org.ccil.cowan.tagsoup.Parser.etag_basic(Parser.java:707)
	at org.ccil.cowan.tagsoup.Parser.etag(Parser.java:645)
	at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:552)
	at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
	at android.text.HtmlToSpannedConverter.convert(Html.java:751)
	at android.text.Html.fromHtml(Html.java:246)
	at android.text.Html.fromHtml(Html.java:200)
	at androidx.core.text.HtmlCompat.fromHtml(HtmlCompat.java:148)
	at com.example.mylibrary.MyPresenter.applyHtml(MyPresenter.kt:11)
	at com.example.mylibrary.MyPresenterSnapshotTest.launchView(MyPresenterSnapshotTest.kt:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app.cash.paparazzi.Paparazzi$apply$statement$1.evaluate(Paparazzi.kt:118)
	at app.cash.paparazzi.agent.AgentTestRule$apply$1.evaluate(AgentTestRule.kt:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by JakeWharton** [comment] 2023-01-20 12:35
Dupe of #689

**Closed by JakeWharton** 2023-01-20 12:35 UTC
Labels: bug
