### ISSUE TITLE
After upgrading to Material3-alphaX - ClassCastException: class java.util.LinkedHashSet cannot be cast to class java.util.List

### ISSUE THREAD

**Issue by Mariius** [cashapp/paparazzi#677] opened 2023-01-06 11:56 UTC
**Description**
After upgrading library `androidx.compose.material3:material3` from version `1.0.1` to `version 1.1.0-alpha1 or alpha2 or alpha3`, paparazzi tests started to fail with the following stacktrace:

```
java.lang.ClassCastException: class java.util.LinkedHashSet cannot be cast to class java.util.List (java.util.LinkedHashSet and java.util.List are in module java.base of loader 'bootstrap')
	at app.cash.paparazzi.Paparazzi.forceReleaseComposeReferenceLeaks(Paparazzi.kt:567)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:208)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:195)
	at com.my.package.button.ButtonKtTest.testDestructiveButton(ButtonKtTest.kt:187)
```

**Additional information:**
- Paparazzi Version: 1.1.0
- Compile SDK: 33
- Gradle Version: 7.4.2
- Android Gradle Plugin Version: 7.3.1

**Comment by JakeWharton** [comment] 2023-01-06 12:46
Dupe of #641

**Closed by JakeWharton** 2023-01-06 12:46 UTC
Labels: bug
